# Generated by Django 5.2 on 2025-04-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pereval_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent', models.IntegerField(verbose_name='родительский id')),
                ('title', models.CharField(max_length=30, verbose_name='название облости')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='время и дата')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Spr_Activities_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='название пути')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='статус')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval_Added',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='время и дата')),
                ('raw_data', models.JSONField(verbose_name='json данные')),
                ('images', models.JSONField(verbose_name='json изображение')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='add_pereval.status', verbose_name='статус записи')),
            ],
        ),
    ]
